name: Update

on:
  schedule:
  - cron: '0 */2 * * *'
  workflow_dispatch:
      
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download files
        shell: bash
        run: |
          mkdir -p module/ipset module/list
          curl -sfL https://antizapret.prostovpn.org/domains-export.txt -o ./module/list/reestr.txt || true
          curl -sfL https://raw.githubusercontent.com/sevcator/zapret-lists/refs/heads/main/.github/workflows/working/ipset.py -o ./module/ipset/ipset.py | true
          sudo apt-get install python
          pip install requests
          cd ./module/ipset/ipset.py
          python ipset.py
          
      - name: Filter subdomains
        shell: bash
        run: |
          sort -u ./module/list/reestr.txt | grep -v '^$' > /tmp/reestr_sorted.txt
          awk -F. '
          {
            n = split($0, a, ".");
            if (n >= 2) {
              print a[n-1] "." a[n];
            }
          }' /tmp/reestr_sorted.txt | sort -u > /tmp/base_domains.txt
          awk -F. '
          BEGIN {
            while ((getline < "/tmp/base_domains.txt") > 0) {
              base[$0] = 1;
            }
          }
          {
            domain = $(NF-1) "." $NF;
            if (!base[domain] || $0 == domain) {
              print $0;
            }
          }' /tmp/reestr_sorted.txt > ./module/list/reestr.txt

      - name: Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add module/ipset/ipset.txt module/list/reestr.txt
          git diff --cached --quiet || git commit -m "Update at $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD:main || echo "No changes to push"
